name: CI - Frontend React App

# Trigger on push to main branch or pull request
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2️⃣ Set up Node.js 18
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3️⃣ Install dependencies
      - name: Install Dependencies
        run: npm ci

      # 4️⃣ Run linter
      - name: Run Linter
        run: npm run lint || true  # continue even if lint fails

      # 5️⃣ Run unit tests
      - name: Run Unit Tests
        run: npm test || true  # continue even if tests fail

      # 6️⃣ Build the application
      - name: Build Application
        run: CI=false npm run build

      # 7️⃣ Log in to Docker Hub
      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 8️⃣ Build and push Docker image
      - name: Build & Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            anubhav1404/user-frontend:latest
            anubhav1404/user-frontend:${{ github.sha }}
