name: CI - Frontend React App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Needed to commit changes

    steps:
      # 1️⃣ Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # 2️⃣ Set up Node.js 18
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3️⃣ Install dependencies
      - name: Install Dependencies
        run: npm ci

      # 4️⃣ Run linter
      - name: Run Linter
        run: npm run lint || true

      # 5️⃣ Run unit tests
      - name: Run Unit Tests
        run: npm test || true

      # 6️⃣ Build the application
      - name: Build Application
        run: CI=false npm run build

      # 7️⃣ Log in to Docker Hub
      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 8️⃣ Build & push Docker image
      - name: Build & Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            anubhav1404/user-frontend:${{ github.sha }}

      # 9️⃣ Update deployment manifest
      - name: Update deployment manifest
        run: |
          sed -i "s|image: .*|image: anubhav1404/user-frontend:${{ github.sha }}|g" kubernetes/frontend-deployment.yaml

      # 🔟 Commit and push manifest changes
      - name: Commit and push manifest changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add kubernetes/frontend-deployment.yaml
          git diff --staged --quiet || git commit -m "CI: Update image tag to ${{ github.sha }}"
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:main
